spring:
  application:
    name: "pocspring"
  datasource:
    url: "jdbc:postgresql://localhost:11432/pocwebframeworks_db"
    username: "pocwebframeworks_user"
    password: "pocwebframeworks_password"
    hikari:
      schema: "pocwebframeworks_schema"
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:11080/iam/realms/poc_web_frameworks/protocol/openid-connect/token/introspect
          client-id: poc_web_frameworks_backend_client
          client-secret: aaNOr50RPAK6yIqDeO6qNLlY7NPKpNJB
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: poc_web_frameworks_backend_client
            client-secret: aaNOr50RPAK6yIqDeO6qNLlY7NPKpNJB
            authorization-grant-type: authorization_code
            client-authentication-method: "client_secret_basic"
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:11080/iam/realms/poc_web_frameworks
            authorization-uri: http://localhost:11080/iam/realms/poc_web_frameworks/protocol/openid-connect/auth
            token-uri: http://localhost:11080/iam/realms/poc_web_frameworks/protocol/openid-connect/token
            user-info-uri: http://localhost:11080/iam/realms/poc_web_frameworks/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:11080/iam/realms/poc_web_frameworks/protocol/openid-connect/certs
            user-name-attribute: sub
server:
  port: 11082
  servlet:
    context-path: "/pocspring"

logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "warn"

management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'prometheus' ]
